postgresql:
  podSecurityContext:
    fsGroup: 0
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    readOnlyRootFilesystem: false
    capabilities:
      drop: []
    seccompProfile:
      type: RuntimeDefault

minio:
  podSecurityContext:
    fsGroup: 0
  containerSecurityContext:
    allowPrivilegeEscalation: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
    readOnlyRootFilesystem: false
    capabilities:
      drop: []
    seccompProfile:
      type: RuntimeDefault
